#!/usr/bin/env bash

set - e

cd "$(dirname "$(readlink - f "$BASH_SOURCE")")"
{
        cat << -'EOH'
       # This File was generated by get_authors.sh. DO NOT EDIT.
       # This file shows the contributor to this project repository.
       # See authors_gen.sh to make modifications and see how it was generated.

        EOH
        echo
        git log - - format = '%aN <%aE>' | LC_ALL = C. UTF - 8 sort - uf
} > AUTHORS
